[tool.ruff]
target-version = "py310"
line-length = 100

src = [ "src" ]
lint.select = [ "ALL" ]
lint.ignore = [
  "ANN",     # Mypy is better at this.
  "C901",    # Leave complexity to me.
  "COM812",  # conflicts with formatter
  "D",       # We have different ideas about docstrings.
  "INP001",  # we don't care that these are in implicit namespace packages
  "ISC001",  # conflicts with formatter
  "PLC0415",
  "PLR0912", # Leave complexity to me.
  "PLR0915", # Leave complexity to me.
  "RUF012",  # no need for this warning in Ansible modules
  "S101",    # assert
  "TID252",  # relative imports make more sense here
  "TRY301",  # Raise in try blocks can totally make sense.
]
lint.unfixable = [ "F401" ]
