from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.tsig_key import TSIGKey
from ...types import UNSET, Response


def _get_kwargs(
    server_id: str,
    *,
    body: TSIGKey,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/servers/{server_id}/tsigkeys".format(server_id=quote(str(server_id), safe="")),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | TSIGKey:
    if response.status_code == 201:
        response_201 = TSIGKey.from_dict(response.json())

        return response_201

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    response_default = Error.from_dict(response.json())

    return response_default


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | TSIGKey]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    server_id: str,
    *,
    client: AuthenticatedClient | Client,
    body: TSIGKey,
) -> Response[Error | TSIGKey]:
    """Add a TSIG key

     This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the
    client

    Args:
        server_id (str):
        body (TSIGKey): A TSIG key that can be used to authenticate NOTIFY, AXFR, and DNSUPDATE
            queries.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TSIGKey]
    """

    kwargs = _get_kwargs(
        server_id=server_id,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    server_id: str,
    *,
    client: AuthenticatedClient | Client,
    body: TSIGKey,
) -> Error | TSIGKey | None:
    """Add a TSIG key

     This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the
    client

    Args:
        server_id (str):
        body (TSIGKey): A TSIG key that can be used to authenticate NOTIFY, AXFR, and DNSUPDATE
            queries.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TSIGKey
    """

    return sync_detailed(
        server_id=server_id,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    server_id: str,
    *,
    client: AuthenticatedClient | Client,
    body: TSIGKey,
) -> Response[Error | TSIGKey]:
    """Add a TSIG key

     This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the
    client

    Args:
        server_id (str):
        body (TSIGKey): A TSIG key that can be used to authenticate NOTIFY, AXFR, and DNSUPDATE
            queries.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TSIGKey]
    """

    kwargs = _get_kwargs(
        server_id=server_id,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    server_id: str,
    *,
    client: AuthenticatedClient | Client,
    body: TSIGKey,
) -> Error | TSIGKey | None:
    """Add a TSIG key

     This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the
    client

    Args:
        server_id (str):
        body (TSIGKey): A TSIG key that can be used to authenticate NOTIFY, AXFR, and DNSUPDATE
            queries.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TSIGKey
    """

    return (
        await asyncio_detailed(
            server_id=server_id,
            client=client,
            body=body,
        )
    ).parsed
