name: CI tests

on:
  workflow_call:
    inputs:
      if:
        required: false
        default: true
        type: boolean
      image:
        required: true
        type: string
      pdns:
        required: true
        type: string
      python:
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    if: inputs.if
    runs-on: ubuntu-24.04-arm
    container:
      image: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
          persist-credentials: false

      - name: start pdns_server
        run: workflow-support/start_server.sh ${INPUTS_PDNS}
        env:
          INPUTS_PDNS: ${{ inputs.pdns }}

      - name: run CI tests
        run: tox run -e${INPUTS_PYTHON}-pdns${INPUTS_PDNS}-ci-action
        shell: bash
        env:
          pdns_version: ${{ inputs.pdns }}
          INPUTS_PYTHON: ${{ inputs.python }}
          INPUTS_PDNS: ${{ inputs.pdns }}
